// Auto-generated by populate-location-coordinates.ts
// Generated on: 2025-07-28T21:04:40.875Z
// Successfully geocoded: 13/13 locations

import { LocationResult } from '@/types/location';

export const POPULATED_LOCATIONS: LocationResult[] = [
  {
    "display_name": "New York, NY, USA",
    "lat": 40.7127281,
    "lon": -74.0060152,
    "type": "city",
    "address": {
      "city": "New York",
      "state": "New York",
      "country": "United States"
    },
  },
  {
    "display_name": "Los Angeles, CA, USA",
    "lat": 34.0536909,
    "lon": -118.242766,
    "type": "city",
    "address": {
      "city": "Los Angeles",
      "state": "California",
      "country": "United States"
    },
  },
  {
    "display_name": "San Francisco, CA, USA",
    "lat": 37.7792588,
    "lon": -122.4193286,
    "type": "city",
    "address": {
      "city": "San Francisco",
      "state": "California",
      "country": "United States"
    },
  },
  {
    "display_name": "Fremont, CA, USA",
    "lat": 37.5482697,
    "lon": -121.988571,
    "type": "city",
    "address": {
      "city": "Fremont",
      "state": "California",
      "country": "United States"
    },
  },
  {
    "display_name": "San Diego, CA, USA",
    "lat": 32.7174202,
    "lon": -117.162772,
    "type": "city",
    "address": {
      "city": "San Diego",
      "state": "California",
      "country": "United States"
    },
  },
  {
    "display_name": "San Jose, CA, USA",
    "lat": 37.3361663,
    "lon": -121.890591,
    "type": "city",
    "address": {
      "city": "San Jose",
      "state": "California",
      "country": "United States"
    },
  },
  {
    "display_name": "Sacramento, CA, USA",
    "lat": 38.5810606,
    "lon": -121.493895,
    "type": "city",
    "address": {
      "city": "Sacramento",
      "state": "California",
      "country": "United States"
    },
  },
  {
    "display_name": "San Gabriel, CA, USA",
    "lat": 34.0990995,
    "lon": -118.1085554,
    "type": "city",
    "address": {
      "city": "San Gabriel",
      "state": "California",
      "country": "United States"
    },
  },
  {
    "display_name": "Chicago, IL, USA",
    "lat": 41.8755616,
    "lon": -87.6244212,
    "type": "city",
    "address": {
      "city": "Chicago",
      "state": "Illinois",
      "country": "United States"
    },
  },
  {
    "display_name": "Miami, FL, USA",
    "lat": 25.7741728,
    "lon": -80.19362,
    "type": "city",
    "address": {
      "city": "Miami",
      "state": "Florida",
      "country": "United States"
    },
  },
  {
    "display_name": "Manassas, VA, USA",
    "lat": 38.7509488,
    "lon": -77.4752667,
    "type": "city",
    "address": {
      "city": "Manassas",
      "state": "Virginia",
      "country": "United States"
    },
  },
  {
    "display_name": "Seattle, WA, USA",
    "lat": 47.6038321,
    "lon": -122.330062,
    "type": "city",
    "address": {
      "city": "Seattle",
      "state": "Washington",
      "country": "United States"
    },
  },
  {
    "display_name": "Austin, TX, USA",
    "lat": 30.2711286,
    "lon": -97.7436995,
    "type": "city",
    "address": {
      "city": "Austin",
      "state": "Texas",
      "country": "United States"
    },
  },
  {
    "display_name": "Houston, TX, USA",
    "lat": 29.7589382,
    "lon": -95.3676974,
    "type": "city",
    "address": {
      "city": "Houston",
      "state": "Texas",
      "country": "United States"
    },
  },
  {
    "display_name": "Dallas, TX, USA",
    "lat": 32.7762719,
    "lon": -96.7968559,
    "type": "city",
    "address": {
      "city": "Dallas",
      "state": "Texas",
      "country": "United States"
    },
  },
  {
    "display_name": "Atlanta, GA, USA",
    "lat": 33.7544657,
    "lon": -84.3898151,
    "type": "city",
    "address": {
      "city": "Atlanta",
      "state": "Georgia",
      "country": "United States"
    },
  },
  {
    "display_name": "Boston, MA, USA",
    "lat": 42.3554334,
    "lon": -71.060511,
    "type": "city",
    "address": {
      "city": "Boston",
      "state": "Massachusetts",
      "country": "United States"
    },
  },
  {
    "display_name": "Philadelphia, PA, USA",
    "lat": 39.9527237,
    "lon": -75.1635262,
    "type": "city",
    "address": {
      "city": "Philadelphia",
      "state": "Pennsylvania",
      "country": "United States"
    },
  },
  {
    "display_name": "Pittsburgh, PA, USA",
    "lat": 40.4416941,
    "lon": -79.9900861,
    "type": "city",
    "address": {
      "city": "Pittsburgh",
      "state": "Pennsylvania",
      "country": "United States"
    },
  },
  {
    "display_name": "Cleveland, OH, USA",
    "lat": 41.4996574,
    "lon": -81.6936772,
    "type": "city",
    "address": {
      "city": "Cleveland",
      "state": "Ohio",
      "country": "United States"
    },
  },
  {
    "display_name": "Detroit, MI, USA",
    "lat": 42.3315509,
    "lon": -83.0466403,
    "type": "city",
    "address": {
      "city": "Detroit",
      "state": "Michigan",
      "country": "United States"
    },
  },
  {
    "display_name": "Minneapolis, MN, USA",
    "lat": 44.9772995,
    "lon": -93.2654692,
    "type": "city",
    "address": {
      "city": "Minneapolis",
      "state": "Minnesota",
      "country": "United States"
    },
  },
  {
    "display_name": "Denver, CO, USA",
    "lat": 39.7392364,
    "lon": -104.984862,
    "type": "city",
    "address": {
      "city": "Denver",
      "state": "Colorado",
      "country": "United States"
    },
  },
  {
    "display_name": "Portland, OR, USA",
    "lat": 45.5202471,
    "lon": -122.674194,
    "type": "city",
    "address": {
      "city": "Portland",
      "state": "Oregon",
      "country": "United States"
    },
  },
  {
    "display_name": "Phoenix, AZ, USA",
    "lat": 33.4484367,
    "lon": -112.074141,
    "type": "city",
    "address": {
      "city": "Phoenix",
      "state": "Arizona",
      "country": "United States"
    },
  },
  {
    "display_name": "Washington, District of Columbia, USA",
    "lat": 38.8950368,
    "lon": -77.0365427,
    "type": "city",
    "address": {
      "city": "Washington",
      "state": "District of Columbia",
      "country": "United States"
    },
  },
  {
    "display_name": "Toronto, Ontario, Canada",
    "lat": 43.6534817,
    "lon": -79.3839347,
    "type": "city",
    "address": {
      "city": "Toronto",
      "state": "Ontario",
      "country": "Canada"
    },
  },
  {
    "display_name": "Vancouver, British Columbia, Canada",
    "lat": 49.2608724,
    "lon": -123.113952,
    "type": "city",
    "address": {
      "city": "Vancouver",
      "state": "British Columbia",
      "country": "Canada"
    },
  },
  {
    "display_name": "Montreal, Quebec, Canada",
    "lat": 45.5031824,
    "lon": -73.5698065,
    "type": "city",
    "address": {
      "city": "Montreal",
      "state": "Quebec",
      "country": "Canada"
    },
  },
  {
    "display_name": "Ontario, Canada",
    "lat": 50.000678,
    "lon": -86.000977,
    "type": "state",
    "address": {
      "state": "Ontario",
      "country": "Canada"
    },
  },
  {
    "display_name": "Calgary, Alberta, Canada",
    "lat": 51.0456064,
    "lon": -114.057541,
    "type": "city",
    "address": {
      "city": "Calgary",
      "state": "Alberta",
      "country": "Canada"
    },
  },
  {
    "display_name": "Paris, Ile-de-France, France",
    "lat": 48.8534951,
    "lon": 2.3483915,
    "type": "city",
    "address": {
      "city": "Paris",
      "state": "Ile-de-France",
      "country": "France"
    },
  },
  {
    "display_name": "London, England, United Kingdom",
    "lat": 51.5074456,
    "lon": -0.1277653,
    "type": "city",
    "address": {
      "city": "London",
      "state": "England",
      "country": "United Kingdom"
    },
  },
  {
    "display_name": "Lisbon, Portugal",
    "lat": 38.7077507,
    "lon": -9.1365919,
    "type": "city",
    "address": {
      "city": "Lisbon",
      "country": "Portugal"
    },
  },
  // {
  //   "display_name": "Sydney, New South Wales, Australia",
  //   "lat": -33.8698439,
  //   "lon": 151.2082848,
  //   "type": "city",
  //   "address": {
  //     "city": "Sydney",
  //     "state": "New South Wales",
  //     "country": "Australia"
  //   },
  // },
  // {
  //   "display_name": "Melbourne, Victoria, Australia",
  //   "lat": -37.8142454,
  //   "lon": 144.9631732,
  //   "type": "city",
  //   "address": {
  //     "city": "Melbourne",
  //     "state": "Victoria",
  //     "country": "Australia"
  //   },
  // },
  {
    "display_name": "New Jersey, USA",
    "lat": 40.0757384,
    "lon": -74.4041622,
    "type": "state",
    "address": {
      "state": "New Jersey",
      "country": "United States"
    },
  },
  {
    "display_name": "California, USA",
    "lat": 36.7014631,
    "lon": -118.755997,
    "type": "state",
    "address": {
      "state": "California",
      "country": "United States"
    },
  },
  {
    "display_name": "Texas, USA",
    "lat": 31.2638905,
    "lon": -98.5456116,
    "type": "state",
    "address": {
      "state": "Texas",
      "country": "United States"
    },
  },
  {
    "display_name": "Florida, USA",
    "lat": 27.7567667,
    "lon": -81.4639835,
    "type": "state",
    "address": {
      "state": "Florida",
      "country": "United States"
    },
  },
  {
    "display_name": "Connecticut, USA",
    "lat": 41.6500201,
    "lon": -72.7342163,
    "type": "state",
    "address": {
      "state": "Connecticut",
      "country": "United States"
    },
  },
  {
    "display_name": "Massachusetts, USA",
    "lat": 42.3788774,
    "lon": -72.032366,
    "type": "state",
    "address": {
      "state": "Massachusetts",
      "country": "United States"
    },
  },
  {
    "display_name": "Illinois, USA",
    "lat": 40.0796606,
    "lon": -89.4337288,
    "type": "state",
    "address": {
      "state": "Illinois",
      "country": "United States"
    },
  },
  {
    "display_name": "Washington, District of Columbia, USA",
    "lat": 38.8950368,
    "lon": -77.0365427,
    "type": "city",
    "address": {
      "city": "Washington",
      "state": "District of Columbia",
      "country": "United States"
    },
  },
  {
    "display_name": "Virginia, USA",
    "lat": 37.1232245,
    "lon": -78.4927721,
    "type": "state",
    "address": {
      "state": "Virginia",
      "country": "United States"
    },
  },
  {
    "display_name": "Pennsylvania, USA",
    "lat": 40.9699889,
    "lon": -77.7278831,
    "type": "state",
    "address": {
      "state": "Pennsylvania",
      "country": "United States"
    },
  },
  {
    "display_name": "New York, USA",
    "lat": 43.1561681,
    "lon": -75.8449946,
    "type": "state",
    "address": {
      "state": "New York",
      "country": "United States"
    },
  },
  {
    "display_name": "Oklahoma, USA",
    "lat": 34.9550817,
    "lon": -97.2684063,
    "type": "state",
    "address": {
      "state": "Oklahoma",
      "country": "United States"
    },
  },
  {
    "display_name": "Hawaii, USA",
    "lat": 19.593801499999998,
    "lon": -155.42837009716908,
    "type": "state",
    "address": {
      "state": "Hawaii",
      "country": "United States"
    },
  },
  {
    "display_name": "British Columbia, Canada",
    "lat": 55.001251,
    "lon": -125.002441,
    "type": "state",
    "address": {
      "state": "British Columbia",
      "country": "Canada"
    },
  },
  {
    "display_name": "Quebec, Canada",
    "lat": 52.4760892,
    "lon": -71.8258668,
    "type": "state",
    "address": {
      "state": "Quebec",
      "country": "Canada"
    },
  },
  {
    "display_name": "Ontario, Canada",
    "lat": 50.000678,
    "lon": -86.000977,
    "type": "state",
    "address": {
      "state": "Ontario",
      "country": "Canada"
    },
  },
  {
    "display_name": "France",
    "lat": 46.603354,
    "lon": 1.8883335,
    "type": "country",
    "address": {
      "country": "France"
    },
  },
  {
    "display_name": "United Kingdom",
    "lat": 54.7023545,
    "lon": -3.2765753,
    "type": "country",
    "address": {
      "country": "United Kingdom"
    },
  },
  {
    "display_name": "Canada",
    "lat": 61.0666922,
    "lon": -107.991707,
    "type": "country",
    "address": {
      "country": "Canada"
    },
  },
  {
    "display_name": "USA",
    "lat": 39.7837304,
    "lon": -100.445882,
    "type": "country",
    "address": {
      "country": "United States"
    },
  },
  {
    "display_name": "Australia",
    "lat": -24.7761086,
    "lon": 134.755,
    "type": "country",
    "address": {
      "country": "Australia"
    },
  },
  {
    "display_name": "Spain",
    "lat": 39.3260685,
    "lon": -4.8379791,
    "type": "country",
    "address": {
      "country": "Spain"
    },
  },
  {
    "display_name": "Portugal",
    "lat": 39.6621648,
    "lon": -8.1353519,
    "type": "country",
    "address": {
      "country": "Portugal"
    },
  }];

// Failed geocoding (requires manual coordinates):
// All locations successfully geocoded!

export function findLocationByName(name: string): LocationResult | undefined {
  return POPULATED_LOCATIONS.find(
    location => location.display_name.toLowerCase().includes(name.toLowerCase()) ||
      location.address?.city?.toLowerCase().includes(name.toLowerCase())
  );
}

export function getLocationCoordinates(name: string): { lat: number; lon: number } | null {
  const location = findLocationByName(name);
  return location?.lat && location?.lon ? { lat: location.lat, lon: location.lon } : null;
}
